FROM #MC_PROJECT#/alpine:latest

LABEL MAINTAINER="David Koenig"

ARG IMAGE_NAME=#MC_PROJECT#/build
ARG IMAGE_VERSION=1.1

ADD setup/#MC_CONFIGFILE#.json /home/appuser/app/config.json

RUN chown appuser:appuser /home/appuser/app/config.json

USER appuser