FROM #MC_PROJECT#/alpine:latest

LABEL MAINTAINER="David Koenig"

ARG IMAGE_NAME=#MC_PROJECT#/build
ARG IMAGE_VERSION=1.1

ADD setup/vault-init.json /home/appuser/app/vault-init.json

RUN chown appuser:appuser /home/appuser/app/vault-init.json

USER appuser