version: '3.7'

services:
  coredns:
    build: 
        dockerfile: Dockerfile-coredns
        context: ./../coredns
    image: frickeldave/coredns:latest
    restart: always
    ports:
     - "53:53/udp"
    volumes:
      - coredns-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "dig", "frickeldave.global"]
      interval: 5s
      timeout: 10s
      retries: 3
  nginx:
    build: 
        dockerfile: Dockerfile-nginx
        context: ./../nginx
    image: frickeldave/nginx:latest
    restart: always
    ports:
      - "443:20443"
    volumes:
      - nginx-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: "curl --fail https://localhost:20443 --insecure || false"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - CRT_VALIDITY=3650
      - CRT_C=DE
      - CRT_S=BAVARIAN
      - CRT_L=HOERGERTSHAUSEN
      - CRT_OU=FRICKELDAVE
      - CRT_CN=PROXY.GLOBAL
  mariadb:
    build: 
      dockerfile: Dockerfile-mariadb
      context: ./../mariadb
    image: frickeldave/mariadb:latest
    restart: always
    ports:
      - "33306:33306"
    volumes:
      - mariadb-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: "mysqladmin status -h 127.0.0.1 -u healthstatus -pfrickeldave2go -P 33306"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - MDB_ROOTPWD=frickeldave2go
      - MDB_PORT=33306
      - MDB_ADMINUSER=adminmdb
      - MDB_BACKUPUSER=backupmdb
      - MDB_ADMINPWD=frickeldave2go
      - MDB_BACKUPPWD=frickeldave2go
      - MDB_HEALTHPWD=frickeldave2go
      - MDB_COLLATION=utf8_unicode_ci
      - MDB_CHARACTERSET=utf8
  gitea:
    build: 
      dockerfile: Dockerfile-gitea
      context: ./../gitea
    image: frickeldave/gitea:latest
    restart: always
    depends_on:
      - mariadb
    ports:
    - "30443:30443"
    volumes:
      - gitea-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:30443", "--insecure"]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - GT_MYSQLADMINUSER=adminmdb
      - GT_MYSQLADMINPASSWORD=frickeldave2go
      - GT_MYSQLHOST=mariadb
      - GT_MYSQLPORT=33306
      - GT_MYSQLDB=gitea
      - GT_MYSQLUSERNAME=gitea
      - GT_MYSQLPASSWORD=gitea2go
      - GT_MYSQLHEALTHUSER=healthstatus
      - GT_MYSQLHEALTHPWD=frickeldave2go
      - GT_PROTOCOL=https
      - GT_HTTP_PORT=30443
      - GT_INITIALADMIN=fdadmin
      - GT_INITIALADMINPWD=Gitea2Go
      - GT_INITIALADMINMAIL=dog-admin@msg.group
      - GT_REMOVE_DB=true
      - CRT_VALIDITY=3650
      - CRT_C=DE
      - CRT_S=BAVARIAN
      - CRT_L=HOERGERTSHAUSEN
      - CRT_OU=FRICKELDAVE
      - CRT_CN=GIT.GLOBAL
volumes:
  mariadb-data:
  nginx-data:
  coredns-data:
  gitea-data:
