version: '3.7'

services:
  alpine:
    build: 
        dockerfile: Dockerfile-alpine
        context: ./../alpine
    image: frickeldave/alpine:latest
  nginx:
    build: 
        dockerfile: Dockerfile-nginx
        context: ./../nginx
    image: frickeldave/nginx:latest
    restart: always
    ports:
      - "443:8443"
    volumes:
      - nginx-data:/home/appuser/data
    networks:
      - default-net
    healthcheck:
      test: "curl --fail https://localhost:8443 --insecure || false"
      interval: 5s
      timeout: 10s
      retries: 3
  mariadb:
    build: 
      dockerfile: Dockerfile-mariadb
      context: ./../mariadb
    image: frickeldave/mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/home/appuser/data
    networks:
      - default-net
    healthcheck:
      test: "mysqladmin status -h 127.0.0.1 -u healthstatus -pfrickeldave2go"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - MDB_ROOTPWD=frickeldave2go
      - MDB_ADMINUSER=adminmdb
      - MDB_BACKUPUSER=backupmdb
      - MDB_ADMINPWD=frickeldave2go
      - MDB_BACKUPPWD=frickeldave2go
      - MDB_HEALTHPWD=frickeldave2go
      - MDB_COLLATION=utf8_unicode_ci
      - MDB_CHARACTERSET=utf8
  # go:
  #   build: 
  #       dockerfile: Dockerfile-go
  #       context: ./../go
  #   image: frickeldave/go:latest
  # godev:
  #   build: 
  #       dockerfile: Dockerfile-godev
  #       context: ./../godev
  #   image: frickeldave/godev:latest
  #   networks:
  #     - default-net
volumes:
  mariadb-data:
  nginx-data:
networks:
  default-net:
    driver: bridge