version: '3.7'

services:
  alpine:
    build: 
        dockerfile: Dockerfile-alpine
        context: ./../alpine
    image: frickeldave/alpine:latest
  build:
    build: 
        dockerfile: Dockerfile-build
        context: .
    image: frickeldave/build:latest  
  mariadbvault:
    build: 
      dockerfile: Dockerfile-mariadb
      context: ./../mariadb
    image: frickeldave/mariadb:latest
    restart: always
    ports:
      - "13306:13306"
    volumes:
      - mariadbvault-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: "mysqladmin status -h 127.0.0.1 -u healthstatus -pfrickeldave2go -P 13306"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - MDB_ROOTPWD=frickeldave2go
      - MDB_PORT=13306
      - MDB_ADMINUSER=adminmdb
      - MDB_BACKUPUSER=backupmdb
      - MDB_ADMINPWD=frickeldave2go
      - MDB_BACKUPPWD=frickeldave2go
      - MDB_HEALTHPWD=frickeldave2go
      - MDB_COLLATION=utf8_unicode_ci
      - MDB_CHARACTERSET=utf8
  go:
    build: 
        dockerfile: Dockerfile-go
        context: ./../go
    image: frickeldave/go:latest
  vault:
    build: 
      dockerfile: Dockerfile-vault
      context: ./../vault
    image: frickeldave/vault:latest
    restart: always
    depends_on:
      - mariadbvault
    ports:
      - "10443:10443"
    volumes:
      - vault-data:/home/appuser/data
    networks:
      - default
    healthcheck:
      test: "curl --fail https://localhost:10443 --insecure || false"
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - VLT_MYSQLADMINUSER=adminmdb
      - VLT_MYSQLADMINPASSWORD=frickeldave2go
      - VLT_MYSQLHOST=mariadbvault
      - VLT_MYSQLPORT=13306
      - VLT_MYSQLDB=vault
      - VLT_MYSQLUSERNAME=vault
      - VLT_MYSQLPASSWORD=vault2go
      - VLT_MYSQLHEALTHUSER=healthstatus
      - VLT_MYSQLHEALTHPWD=frickeldave2go
      - VLT_IPADDRESS=0.0.0.0
      - VLT_PORT=10443
      - VLT_REMOVE_DB=true
      - CRT_VALIDITY=3650
      - CRT_C=DE
      - CRT_S=BAVARIAN
      - CRT_L=HOERGERTSHAUSEN
      - CRT_OU=FRICKELDAVE
      - CRT_CN=VAULT.GLOBAL
volumes:
  mariadbvault-data:
  vault-data:
  gitea-data:
